---
- name: Adyen
  grade: B
  url: https://github.com/Adyen/adyen-openapi
- name: Amazon Partners
  grade: B
  url: https://github.com/amzn/selling-partner-api-models
- name: Asana
  grade: B
  url: https://github.com/Asana/openapi
- name: Azure
  grade: B
  url: https://github.com/Azure/azure-rest-api-specs
- name: BigCommerce
  grade: B
  url: https://github.com/bigcommerce/docs
- name: Box
  grade: B
  url: https://github.com/box/box-openapi
- name: CloudFlare
  grade: C
  url: https://github.com/cloudflare/api-schemas
- name: Digital Ocean
  grade: A
  url: https://github.com/digitalocean/openapi
- name: Discord
  grade: B
  url: https://github.com/discord/discord-api-spec
- name: DocuSign
  grade: B
  url: https://github.com/docusign/OpenAPI-Specifications
- name: Dropbox
  grade: B
  url: https://github.com/dropbox/dropbox-api-spec
- name: Dropbox Sign
  grade: B
  url: https://github.com/hellosign/hellosign-openapi
- name: Fiware
  grade: B
  url: https://github.com/FIWARE/specifications
- name: GitHub
  grade: B
  url: https://github.com/github/rest-api-description
- name: Launch Darklys
  grade: B
  url: https://github.com/launchdarkly/ld-openapi
- name: Netlify
  grade: B
  url: https://github.com/netlify/open-api
- name: New York Times
  grade: C
  url: https://github.com/nytimes/public_api_specs
- name: Okta
  grade: B
  url: https://github.com/okta/okta-management-openapi-spec
- name: OpenAI
  grade: C
  url: https://github.com/openai/openai-openapi
- name: Paypal
  grade: B
  url: https://github.com/paypal/paypal-rest-api-specifications
- name: Phrase
  grade: B
  url: https://github.com/phrase/openapi
- name: Plaid
  grade: C
  url: https://github.com/plaid/plaid-openapi
- name: ShipEngine
  grade: B
  url: https://github.com/ShipEngine/shipengine-openapi
- name: Slack
  grade: B
  url: https://github.com/slackapi/slack-api-specs
- name: Stripe
  grade: B
  url: https://github.com/stripe/openapi
- name: Twilio
  grade: B
  url: https://github.com/twilio/twilio-oai
- name: VTEX's
  grade: B
  url: https://github.com/vtex/openapi-schemas
- name: Snowflake
  grade: B
  url: https://github.com/snowflakedb/snowflake-rest-api-specs