- name: Strategy
  slug: strategy
  image: /images/strategy.png
  description: Helping define the overall API lifecycle and governance strategy, working with internal teams to evolve existing strategy, or help define a new strategy, bringing the experience you need to augment your existing resources.
  tags:
    - Services
    - Strategy
    - 3rd-Party
    - Producers 
- name: Program
  slug: program
  image: /images/programs.png
  description: Laying the ground for your API governance program, providing the lifecycle, policies, rules, schema, and contracts to kick-off your efforts, while laying the foundation for an API governance program that you can scale over time. 
  tags:
    - Services
    - Strategy
    - 3rd-Party
    - Producers         
- name: Platform
  slug: platform
  image: /images/platforms.png
  description: Defining the infrastructure beneath API operations, providing a common definition of the resources and capabilities needed across the API lifecycle, allowing for self-service and automation across the teams who are producing APIs. 
  tags:
    - Services
    - Strategy
    - 3rd-Party
    - Producers      
- name: Policies
  slug: policies
  image: /images/policies.png
  description: Getting formal about the business of why you need API governance and properly wrapping your rules with the business rationale for why you do things like versioning, status codes, and other essentials to better align API operations.
  tags:
    - Services
    - Strategy
    - 3rd-Party
    - Producers  
- name: Lifecycle
  slug: lifecycle
  image: /images/lifecycle.png
  description: Get explicit about what each stage of the API producer and consumer lifecycle, as well as what actually occurs within each stage, organizing your governance rules by lifecycle stage to keep APIs moving forward across teams.
  tags:
    - Services
    - Strategy
    - 3rd-Party
    - Producers  
- name: Schema
  slug: schema
  image: /images/schema.png
  description: Defining the custom schema you need to round-off your API contracts with the business and technical details you need produce APIs, ensuring the language you need for your API contracts properly defines what is happening. 
  tags:
    - Services
    - Strategy
    - 3rd-Party
    - Producers  
- name: Rules
  slug: rules
  image: /images/rules.png
  description: Developing the machine-readable governance rules you need to validate and certify your API contracts in full, providing the rules, but also the automation needed to keep APIs moving forward in a consistent and repeatable way.
  tags:
    - Services
    - Strategy
    - 3rd-Party
    - Producers   
- name: Mapping
  slug: mapping
  image: /images/mapping.png
  description: Mapping the landscape of APIs, defining one or many contracts that already exist, helping to better understand the scope of existing API operations, and organize based upon the bounded context that matters most to leadership.
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers      
- name: Creation
  slug: creation
  image: /images/creation.png
  description: The creation of APIs.json business, OpenAPI technical, and other properties of a contract that are machine-readable, helping lay the groundwork for your API contracts, then helping guide you in refining and evolving them over time.
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers   
- name: Review
  slug: review
  image: /images/reviews.png
  description: Providing reviews of API contracts to identify existing patterns in use across API operations, then also providing feedback on anti-patterns, as well as additional patterns that could be applied to help improve API operations. 
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers     
- name: Certification
  slug: certification
  image: /images/certification.png
  description: Certification of the properties of a contract, ensuring that they exist and are up to standards, and that individual API operations are accessible and are aligned with business use cases and are acceptable with contract schema.
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers   
- name: Mediation
  slug: mediation
  image: /images/mediation.png
  description: Provide mediation services when there are disagreements between owners and stakeholders producing APIs, as well as between producers and consumers over the business or technical details of an API, helping establish alignment.   
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers   
- name: Nudges
  slug: nudges
  image: /images/nudges.png
  description: Weekly nudges on an agreed upon day regarding any questions, feedback, and changes being proposed by both API producer or consumer, helping keep the API lifecycle moving forward and maintain agreed upon levels of activity.    
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers 
- name: Guidance
  slug: guidance
  image: /images/guidance.png
  description: Modular educational resources for APIs and API operations, providing markdown resources that provide an overview, but also insights into the business, technology, policies, and people side of API operations.
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers        
- name: Evangelism
  slug: evangelism
  image: /images/evangelism.png
  description: Helping enable you to evangelize your API lifecycle, policies, and guidance across your teams, and within your industry, helping build more awareness and gather feedback from stakeholders across your API operations.
  tags:
    - Services
    - Contract
    - 3rd-Party
    - Producers       