---
layout: post
title: 'History of APIs - Google Maps API'
source: http://apievangelist.com/2011/01/30/history-of-apis--google-maps-api/
domain: apievangelist.com
image: 
---
<p>On June 29th, 2006,&nbsp;<a href="http://googleblog.blogspot.com/2005/06/world-is-your-javascript-enabled_29.html" target="_blank">Google launched Google Maps API</a>&nbsp;allowing developers to put Google Maps on their own sites using JavaScript.</p>
<p>The API launch was just shy of 6 months after the&nbsp;<a href="http://googleblog.blogspot.com/2005/02/mapping-your-way.html" target="_blank">release of Google Maps as an application</a>, and was in direct response to the number of rogue applications developed that were hacking the application.&nbsp;<a href="http://code.google.com/apis/maps/index.html" target="_blank"><img src="http://kinlane-productions.s3.amazonaws.com/google/google-map-logo.gif" alt="" width="250" align="right" /></a>Google Maps was immediately so popular that developers hacked the JavaScript interface and developed application such as<a href="http://www.http//googleblog.blogspot.com/2005/02/mapping-your-way.html" target="_blank">housingmaps.com</a>&nbsp;and&nbsp;<a href="http://www.chicagocime.org">chicagocime.org</a>. The demand was so great for information on hacking Google Maps it spawned books such as&nbsp;<a href="http://oreilly.com/catalog/9780596007034" target="_blank">Mapping Hacks</a>&nbsp;and&nbsp;<a href="http://oreilly.com/catalog/9780596004477" target="_blank">Google Hacks</a>&nbsp;from&nbsp;<a class="zem_slink" title="O'Reilly Media" rel="homepage" href="http://www.oreilly.com/">O'Reilly</a>.</p>
<p><a href="http://code.google.com/apis/maps/index.html" target="_blank">Google Maps API</a>&nbsp;started a trend of API mashups with its valuable location based data, with over 2000 mashups to date.</p>
<p>The API demonstrates the incredible value of&nbsp;<a class="zem_slink" title="Geographic data" rel="wikipedia" href="http://en.wikipedia.org/wiki/Geographic_data">geographic data</a>&nbsp;and mapping&nbsp;<a href="http://www.apievangelist.com/">APIs</a>, as well as the power users can have in influencing the direction an application or API takes. Lars Rasmussen, the original developer of Google Maps commented how much he learned from the developer community by watching how they hacked the application in real-time, and they took what they learned and applied it to the API we know today.</p>