---
layout: post
title: 'Would You Pay For Alternate Options For An API Terms Of Service?'
source: http://apievangelist.com/2014/05/01/would-you-pay-for-alternate-options-for-an-api-terms-of-service/
domain: apievangelist.com
image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-politics.png
atomdate: 2014-05-01T20:06:49-07:00
---
<p><img class="c1" src="https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-politics.png" alt="" width="200" align="right" /></p>
<p>Terms of service <a href="http://apievangelist.com/2014/04/10/the-levers-dials-and-switches-for-your-participation-in-the-api-economy/">guide every aspect of how we provide and consume an APIs</a>&nbsp;that drive&nbsp;our web and mobile applications. As an excercise, lets imagine a future where API terms of service (TOS) are machine readable, and always in alignment with the multiple partner tiers, and the service composition of an API platform.</p>
<p>Right now, the options available to API consumers is organized into service packages, allowing us multiple tiers of access, based upon usage + cost, when registering for and consuming API resources. Imagine if during this process the API TOS were integrated into the registration and account management workflows. Imagine you could fully understand each portion of the API TOS, and be provided with options, instead of a single, rigid level of service.</p>
<p>Currently <a href="http://apievangelist.com/2014/03/17/politics-of-apis/">options for API access are throttled across TOS, privacy policy, branding, service level agreements, pricing, and service composition and partner access tiers</a>. I want to explore the possibility that these building blocks could be machine readable, allowing for variances on each aspect of API operations. This scenario would allow for API consumers to prioritize which aspects of operations are most important to them, allowing them to pay more for premium access to API services.</p>
<p>I&rsquo;m just working through my thoughts on the <a href="http://apievangelist.com/2014/03/17/politics-of-apis/">politics of APIs</a>, expanding on ideas of machine readable terms of service (TOS) introduce to me by Tyler Singletary (<a href="https://twitter.com/harmophone">@harmophone</a>)&nbsp;of <a href="https://twitter.com/KloutAPI">@KloutAPI,</a> and also a tweet from Antony Falco (<a href="https://twitter.com/antonyfalco">@antonyfalco</a>)&nbsp;of <a href="http://orchestrate.io/">Orchestrate.io</a>&nbsp;about the potential to allow for variances of TOS.</p>
<p>I would love to hear your thoughts on this subject. Am I off in left field, or is this something we should play with more?</p>