---
layout: post
title: 'APIs Will Not Be Suffocated By Oracle and the Courts, It Will Be Done By Each Of You Not Sharing Your API Designs'
source: http://apievangelist.com/2015/06/29/apis-will-not-be-suffocated-by-oracle-and-the-courts-it-will-be-done-by-each-of-you-not-sharing-your-api-designs/
domain: apievangelist.com
image: http://apicommons.org"><img src="https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
---

<p><a href="http://apicommons.org"><img src="https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png" alt="" width="200" align="right" /></a></p>
<p><a href="http://recode.net/2015/06/29/u-s-top-court-declines-to-hear-google-appeal-in-oracle-software-fight/">I just read on Re/Code, that the Supreme Court declined to hear Google's appeal on the Oracle v Google case</a>--prepare for the waves of stories from tech blogs, that this will suffocate the API economy. During the last response to the case by the US Solicitor General, <a href="http://apievangelist.com/2015/05/28/regarding-the-solicitor-general-weighing-in-on-the-oracle-v-google-api-copyright-case-are-you-really-surprised-they-do-not-get-apis-i-am-not/">I wrote about how I can't even argue the concept anymore</a>, and nothing has changed for me.&nbsp;</p>
<p>I just wanted to take the moment to remind everyone that this decision means nothing if we all share our API definitions, in open ways, using machine readable definitions like <a href="http://apiblueprint.org">API Blueprint</a> and <a href="http://swagger.io">Swagger</a>. The disturbing move by Oracle to bring a lawsuit against Google, and the very unaware decision(s) made all the way up to federal level, will NOT bring down the API economy--your inaction will!</p>
<p>If I've learned anything during my time defending APIs, as part of the Oracle v Google case, is that many of you are holding your API designs close to your chest, thinking maybe, just maybe, they are intellectual property we should protect, and can make money on, when we are the next unicorn start-up. You are willing to do this, even at the expense of the success of your APIs, ignoring that it creates huge amounts of friction with developers, and the businesses you are asking to integrate your APIs into their systems.</p>
<p>When you bundle this with the large numbers of folks who don't even understand the difference between an API definition or design, and its code back-end, you end up with a very dangerous, controllable group of folks, who will slowly stifle, and potentially suffocate any momentum we have built with the API economy. It will be these groups of individuals and companies, who will blindly do Oracle's bidding, and make sure any democratizing power APIs had, stays in the hands of the powerful few.</p>
<p>Why would anyone integrate your API definition into their application, if at some point they can be forced to license and pay for the naming, and order of API endpoints that are called? I sure wouldn't. <a href="http://techcrunch.com/2013/11/05/3scale-launches-api-commons-to-allow-developers-to-share-apis-under-creative-commons-licenses/">This is why Steve Willmott and I started API Commons</a>, so that we can start sorting out the open API definitions, from the closed ones, and <a href="http://apisjson.org">index these API operations using APIs.json</a>, allowing the API economy to filter itself at run-time, leaving closed, potentially dangerous definitions behind.</p>
<p>Please join me in the fight, by helping me define the common API patterns available across the space, as part our&nbsp;<a href="http://theapistack.com">the API Stack</a>&nbsp;work--do not let this decision get you down.</p>