---
layout: post
title: 'Hypermedia APIs From S&eacute;bastien Cevey of The Guardian at @APIDaysBerlin / @APIStrat Next Week'
sourceurl: http://apievangelist.com/2015/04/14/hypermedia-apis-from-sbastien-cevey-of-the-guardian-at-apidaysberlin--apistrat-next-week/
image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/blog/the-guardian-open-platform.jpeg
---

<p><a href="http://open-platform.theguardian.com/"><img style="padding: 15px;" src="http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/blog/the-guardian-open-platform.jpeg" alt="" width="290" align="right" /></a></p>
<p>The most important stories told across the API space, the ones that have the biggest impact on API providers, and ultimately API consumers, are the stories that come out of the trenches of the API operations at the leading public API providers. This is why 3Scale and API Evangelist started APIStrat, and what the audiences over the last 3 years of operating APIDays and APIStrat have consistently requested--more stories from the trenches.</p>
<p>With this in mind, we've asked S&eacute;bastien Cevey (<a href="https://twitter.com/theefer">@theefer</a>) of The Guardian to come to <a href="http://apidaysberlin2015.apistrat.com/">@APIDaysBerlin / @APIStrat Europe 2015</a>, and share a story from API operations at the worlds leading media API provider. S&eacute;bastien wanted to share their view of what Hypermedia APIs are, by comparing them to a classical RPC architecture and ad-hoc "JSON APIs". He will also cover key benefits of using Hypermedia APIs (cacheability, discoverability, evolveability/extensibility, simplicity, interactive nature), presented in the context of real-world examples and the different constraints of REST (HTTP, URIs, verbs, hypermedia controls like links and forms).</p>
<p><a href="https://twitter.com/theefer"><img style="padding: 15px;" src="http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/blog/sebastien-sevey-the-guardian.jpg" alt="" width="200" align="right" /></a></p>
<p>What I like about S&eacute;bastien viepoint, is 1) he works at one of the most progressive media outlets in the world, where he is actually putting APIs to work, and 2) his pragmatic approach. S&eacute;bastien will talk about what hypermedia APIs are, anchoring his lessons in real-world examples from Guardian operations, but he will also discuss the caveats of this API style, acknowledging the realities of API operations. There are no perfect solutions, but technologists like S&eacute;bastien&nbsp;are pushing the discipline of API design forward, while also balancing with the real-world reality that exists in their workplaces.</p>
<p>The keynote from S&eacute;bastien Cevey (@theefer) of The Guardian, <a href="http://apidaysberlin2015.apistrat.com/schedule/">will kick off the first day of @APIDaysBerlin / @APIStrat Europe 2015</a>, so <a href="http://apidaysberlin2015.apistrat.com/#tile_registration">make sure you are registered today</a>, so you don't get locked out when we sell out (which we are very close). If you are looking to learn more about hypermedia APIs, I recommend starting with S&eacute;bastien's keynote, but also make sure and join us Saturday morning for the entire hypermedia API session, where you can learn more about this fast growing API design consideration, from those pushing the conversation forward, and putting hypermedia APIs to work in the real world.</p>
<p>I look forward to seeing you all in Berlin, next week!</p>