---
layout: post
title: 'The Growing Need For API Virtualization Solutions'
source: http://apievangelist.com/2015/12/01/the-growing-need-for-api-virtualization-solutions/
domain: apievangelist.com
image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-virtulization.png
atomdate: 2015-12-01T21:13:24-08:00
---
<p><img src="https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-virtulization.png" alt="" width="225" align="right" /></p>
<p>This conversation has come up over 10 times this month, at <a href="http://defragcon.com/">Defrag</a>, <a href="http://austin2015.apistrat.com/">APIStrat</a>, and online conversations via Skype and GHangouts. The concept of API virtualization solutions. I am not talking about virtualization in the cloud computing and Docker sense, although that will play a fundamental role in the solutions I am trying to articulate. What I am focusing on is about providing sandbox, QA environments, and other specialized virtualization solutions for API providers, that make API consumers worlds much easier.&nbsp;</p>
<p>I've touched on examples of this in the wild, with <a href="http://apievangelist.com/2014/11/05/api-sandbox-and-simulator-from-carvoyant/">my earlier post on&nbsp;API sandbox and simulator from Carvoyant</a>, which is an example of the need for virtualization solutions that are tailored for the connected automobile solution. Think of this, but for every aspect of the fast growing Internet of Things space. The IoT demand is about the future opportunity, I've talked about the current need, when I published, <a href="http://apievangelist.com/2015/07/11/i-wish-all-apis-had-sandbox-environment-by-default/">I Wish All APIs Had Sandbox Environment By Default</a>.</p>
<p>I see envision 1/3 of these solutions being about deploying Docker containers on demand, 1/3 being about virtualizing the API using common API definitions, and the final 1/3 being about the data provided with the solutions. This is where I think the right team(s) could develop some pretty unique skills when it comes to delivering specialized simulations tailored for testing home, automobile, agriculture, industrial, transportation, and other unique API solutions.</p>
<p>We are going to need "virtualized" versions of our APIs, whether or not it is for web, mobile, devices, or just for managing APIs throughout their life cycle. You can see a handful of the <a href="http://virtualization.apievangelist.com/">current API virtualizations out there on my research in this area</a>, but I predict the demand for more robust, and specialized API virtualization solutions is going to dramatically increase as the space continues its rapid expansion. I just wanted to put it out there, and encourage all y'all to think more about this area, and push forward the concept of API virtualization as you are building all the bitch'n tooling you are working on.</p>