---
published: true
layout: post
title: 'I Will See You At APIStrat In Portland This November'
image: https://s3.amazonaws.com/kinlane-productions2/apistrat/apistrat-portland-screenshot.png
---

<p><img src="https://s3.amazonaws.com/kinlane-productions2/apistrat/apistrat-portland-screenshot.png" align="right" width="40%" style="padding: 15px;" />
<p><a href="http://events.linuxfoundation.org/events/apistrat/program/schedule">We are putting the finishing touches on the schedule for APIStrat in Portland, OR, October 31st through November 2nd</a>. We have all the workshops, sessions, and keynotes dialed in (not all keynotes announced, wink, wink), and it is all just about making sure y’all show up and participate in the conversation. This is my 2nd favorite part of the event, the build-up for the big day(s). This is the 8th APIStrat we’ve done, and it is the first one we’ve done as part of the Linux Foundation, and with the OpenAPI Initiative. I’m excited.

<p><a href="http://events.linuxfoundation.org/events/apistrat/program/schedule">Make sure and take a look at the session schedule</a>. We received over 165 submissions, and had a program committee of almost 30 people vote to decide with 60 would be accepted. I am the program chair and helped make some difficult decisions, but ultimately I”m pretty proud of the lineup we’ve pulled together. It’s much of the same popular topics as you’ve seen at previous events, with new faces, and brands, but there is also some of the leading edge conversations around serverless, gRPC, GraphQL. Of course, there is also going to be a lot of talk about OpenAPI, in workshops, sessions, and on the main stage. So check out the schedule if you haven’t, it’s pretty sweet lineup.

<p>I want to personally thank <a href="https://www.microsoft.com/">Microsoft</a>, Stoplight, <a href="https://smartbear.com/">SmartBear</a>, <a href="https://www.postman.com/">Postman</a>, <a href="https://developer.capitalone.com/">CapitalOne DevExchange</a>, <a href="https://apimatic.io/">APIMATIC</a>, <a href="https://www.redhat.com/">Red Hat</a>, <a href="https://cloud.google.com/">Google</a>, and <a href="http://www.cloud-elements.com/">Cloud Elements</a> for <a href="http://events.linuxfoundation.org/events/apistrat/sponsors/our-sponsors">sponsoring and making sure APIStrat happens</a>. Of course, thank you to <a href="https://www.linuxfoundation.org/">The Linux Foundation</a>, and the <a href="https://www.openapis.org/">OpenAPI Initiative (OAI)</a> for taking the lead on APIStrat as it continues to grow and mature with the API community. I want to also thank my partner in crime, Steve Willmott, and the 3Scale / Red Hat team–without them APIStrat wouldn’t be a thing.

<p>Next up for me, now that the schedule is dialed in. Is to just tell stories about what will be happening. I’m going to go through each of the speakers, and companies who are present and look to see what they are up to with APIs. It is something I always try to do in the final months of build up to the conference. APIStrat has been an important part of how I learn about what is going on with APIs, and who the interesting companies, and people are. Hopefully it is the same for you, and we can both be there in November, and learn what is going on together. It will be my first event where I’m not giving a talk. ;-) I’ll still be MC’ing, and harassing y’all in the hallways, but I’m looking forward to being able to tune into more of the talks as they occur.

