---
published: true
layout: post
title: 'The Growing Importance of Geographic Regions In API Operations'
image: https://s3.amazonaws.com/kinlane-productions2/3D-Printing/regions/api-regions-global-map-from-google.png
---

<p><a href="https://cloud.google.com/about/locations/"><img src="https://s3.amazonaws.com/kinlane-productions2/3D-Printing/regions/api-regions-global-map-from-google.png" align="right" width="40%" style="padding: 15px;" /></a>
<p>I have been revisiting <a href="http://apievangelist.com/2015/10/31/how-are-we-going-to-create-the-standard-and-poors-and-moodys-for-the-api-economy/">my earlier work on an API rating system</a>. One area that keeps coming up as I’m working is around the availability of APIs in a variety of regions, and the cloud platforms that are driving them. <a href="http://apievangelist.com/2011/02/04/launch-region-specific-apis/">I have talked about regional availability of APIs</a> for some time now, keeping an eye on <a href="http://apievangelist.com/2016/01/05/your-api-access-replicated-into-multiple-regions-around-the-globe-for-additional-charge/">how API providers are supporting multiple regions</a>, as well as <a href="http://apievangelist.com/2017/05/08/regional-availability-when-it-comes-to-api-access/">the expanding world of cloud computing</a> that is powering these regional examples of providing and consuming APIs.

<p>I have been watching <a href="https://docs.aws.amazon.com/general/latest/gr/rande.html">Amazon rapidly expand their available regions</a>, as well as <a href="https://cloud.google.com/compute/docs/regions-zones/regions-zones">Google</a> and <a href="https://azure.microsoft.com/en-us/regions/">Microsoft</a> racing to catch up. But I am starting to see API providers <a href="https://developers.digitalocean.com/documentation/v2/#regions">like Digital Ocean providing APIs for getting at geographic region information</a>, and <a href="https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html">Amazon provides API methods for getting the available regions for Amazon EC2 compute</a>–I will have to check if this is standard across all services. <a href="https://www.twilio.com/docs/api/client/regions">Twilio has regions for their API client</a>, and <a href="https://www.runscope.com/docs/api/regions">Runscope has a region API for managing how you run API tests from a variety of regions</a>. The role of geographic regions when it comes to providing APIs, as well as consuming APIs is increasingly part of the conversation when you visit the most mature API platforms, and something that keeps coming up on my radar.

<p>We are still far from the average company being able to easily deploy, deprecate, and migrate APIs seamlessly across cloud providers and geographic regions, but as APIs become smaller and more modular, and cloud providers add more regions, and APIs to support automation around these regions, we will begin to see more decisions being made at deploy and run time regarding where you want to deploy or consume your API resources. To be able to do this we are going to need a lot more data and common schema regarding the what geographic regions are available for deployment, what services operate in which regions, and other key considerations about exactly where our resources should operate. This is why I’m revisiting this work, to see what I can do to get API service providers to share more data from either the API provider or consumer side of the equation.

<p>I am considering adding an area of my research dedicated to API regions, aggregating examples of how geographic regions are playing a role in API operations. I’m thinking region availability will be playing just as significant role as <a href="http://performance.apievangelist.com">performance</a>, <a href="http://plans.apievangelist.com">plans</a>, <a href="http://security.apievangelist.com">security</a>, <a href="http://reliablity.apievangelist.com">reliability</a>, and other areas of the API lifecycle when it comes to deciding where you deploy or consume your APIs. It feels like another one of the aspects of API operations that will overlap with many stops along the API lifecycle–not just <a href="http://deployment.apievangelist.com">deployment</a>. One of the areas of the API lifecycle I’m increasingly thinking about that will affect geographic API decisions is <a href="http://regulation.apievangelist.com">regulations</a>, and how governments are dictating what is acceptable when it comes to the storage, transmission, and access of digital resources. It feels like early notions of what the World Wide Web has been for the last 25 years is about to be blown out of the water, with the influences of digital nationalism, regulation, or even the Internet moving off planet, and increasingly driven by satellite infrastructure.

