---
published: true
layout: post
title: 'Facebook Quietly Deprecates The Audience Insight API Used To Automate'
image: blished: true
---

<p><img src="https://s3.amazonaws.com/kinlane-productions2/facebook/audience-insights/facebook-audience-insights-api-affinity.png" align="right" width="45%" style="padding: 15px;" />
<p><a href="http://www.adweek.com/digital/facebook-is-shutting-down-its-api-that-marketers-lean-on-for-research/#/">According to AdWeek, Facebook is quietly shutting down its Audience Insights API by the end of the year</a>. They have a statement from Facebook stating, “We have decided to focus marketers on our more broadly available Audience Insights tool, so we are winding down the Audience Insights API by end of year. We’ll continue testing different ways to provide valuable insights to advertisers and agencies through the tool and across other destinations on Facebook.” which I assume they got directly from Facebook, because I can find no other communication regarding the deprecation of the API through normal <a href="https://newsroom.fb.com/">newsroom</a>, or <a href="https://developers.facebook.com/docs/graph-api/changelog">API change log</a> channels. It could be that I’m missing it, but it is clear they are trying to minimize chatter around this.

<p>According to <a href="https://www.facebook.com/business/help/304781119678235">the Facebook help page</a>, Audience Insights, “shows you data about your target audiences so that you can create more relevant advertisements for them”. The platform uses native Facebook data to show you audience features such as: Age and gender, Relationship status, Education level, Job role, Top categories, Page likes, Top cities, Top countries, Top languages, Frequency of activities, and Device users. Then using third-party data (data come from sources like Acxiom, Datalogix and Epsilon) they show you audience features such as: Lifestyle, Household income, Home ownership, Household size, Home market value, Spending methods, Retail spending, Online purchases, Purchase behavior, and whether they are in market for a vehicle. You can still get at this via <a href="https://www.facebook.com/ads/audience-insights/">the Facebook Audience Insights web interface</a>, but the APIs for automating this aspect of Facebook has mostly disappeared, or is in the process of disappearing.

<p>There are three layers to the Faceook Audience Insights API deprecation. You can still access some insights for ads, pages, and other objects, as well as one audience insight still available:

<ul>
  <li><a href="https://developers.facebook.com/docs/graph-api/reference/v2.11/insights"><strong>/{object-id}/insights</strong></a>  - Facebook Insights is a product available to all Pages and Apps on Facebook using the Insights dashboard.</li>
  <li><a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-rule/"><strong>Audience Insights Rule</strong></a> - Definition of an audience insight rule.</li>
</ul>

<p>Then there are a handful of API paths related to Audience Insights that are still there, but not listed off the main navigation:

<ul>
  <li><a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-rule-component/"><strong>Audience Insights Rule Component</strong></a> - Rule component of a study rule.</li>
  <li><a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-post/"><strong>Audience Insights Post</strong></a> - Represents a sample post.</li>
  <li><a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-group-by-summary/"><strong>Audience Insights Group By Summary</strong></a> - Overall summary for audience insights query insights.</li>
  <li><a href="https://developers.facebook.com/docs/graph-api/reference/insights-value/"><strong>Insights Value</strong></a> - The value for one insights metric given a timestamp.</li>
  <li><a href="https://developers.facebook.com/docs/graph-api/reference/insights-result/"><strong>Insights Result</strong></a> - The result of an Insights query.</li>
</ul>

<p>Then there are the core Audince Insights APIs that are completely gone, with all documentation removed:

<ul>
  <li><strong>Audience Insights Lifestyles</strong> (<a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-lifestyles/">URL</a>) (<a href="https://webcache.googleusercontent.com/search?q=cache:zcVvTrCjRTYJ:https://developers.facebook.com/docs/graph-api/reference/audience-insights-lifestyles/+&amp;cd=1&amp;hl=en&amp;ct=clnk&amp;gl=us">Cached URL</a>) - Insights about lifestyles for you audience.</li>
  <li><strong>Audience Insight Education Level</strong> (<a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-education-level/">URL</a> (<a href="https://webcache.googleusercontent.com/search?q=cache:AxUtpiQ0vuIJ:https://developers.facebook.com/docs/graph-api/reference/audience-insights-education-level/+&amp;cd=1&amp;hl=en&amp;ct=clnk&amp;gl=us">Cached URL</a>) - Information about the education level of your audience</li>
  <li><strong>Audience Insights Home Owners</strong> (<a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-home-owners/">URL</a> (<a href="https://webcache.googleusercontent.com/search?q=cache:8KLILtYG3KYJ:https://developers.facebook.com/docs/graph-api/reference/audience-insights-home-owners/+&amp;cd=1&amp;hl=en&amp;ct=clnk&amp;gl=us">Cached URL</a>) - Information about home ownership.</li>
  <li><strong>Audience Insights Household Income</strong> (<a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-household-income/">URL</a> (<a href="https://webcache.googleusercontent.com/search?q=cache:um_yOLJk-lYJ:https://developers.facebook.com/docs/graph-api/reference/audience-insights-household-incomes/+&amp;cd=1&amp;hl=en&amp;ct=clnk&amp;gl=us">Cached URL</a>) - Household incomes information about your audience.</li>
  <li><strong>Audience Insights Purchase Behaviors</strong> (<a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights-purchase-behaviors/">URL</a> (<a href="https://webcache.googleusercontent.com/search?q=cache:7GPqnSgOYVIJ:https://developers.facebook.com/docs/graph-api/reference/audience-insights-purchase-behaviors/+&amp;cd=1&amp;hl=en&amp;ct=clnk&amp;gl=us">Cached URL</a>) - Purchase behaviors information for your audience.</li>
  <li><strong>Audience Insights Affinity</strong> (<a href="https://developers.facebook.com/docs/graph-api/reference/audience-insights">URL</a> (<a href="https://webcache.googleusercontent.com/search?q=cache:rhIkcFkbT7YJ:https://developers.facebook.com/docs/graph-api/reference/audience-insights-affinity/+&amp;cd=1&amp;hl=en&amp;ct=clnk&amp;gl=us">Cached URL</a>) - Information about the affinity for a given page.</li>
</ul>

<p>These are the six API paths that you would use to scale and automate any information, or disinformation campaign. This is how you develop, evolve, and act upon your models when it comes to publishing Facebook Pages, buying advertising and spreading video, photos, news, and other (dis)information that you are targeting your users with. I see hints of these insight API going away on <a href="https://developers.facebook.com/docs/graph-api/changelog/version2.11">the most recent November 7th update</a>, but there are <a href="https://developers.facebook.com/docs/graph-api/changelog/version2.10#mapi-deprecate">no marketing API deprecations in the last one in July that changed how you are able share links via the API</a>–something that was a response to the election backlash. The last cache of the missing documentation pages was on November 9th, showing they’ve been actively working in November to clean things up, and by the looks of things they are still working on this.

<p>Ok, many might say that this is a good thing. Facebook is removing the tools that allow you to automate these types of campaigns. Limiting who has access to them. Sure. However, it doesn’t stop them from still providing access to partners, and other folks behind the scenes, further reducing any observability into the process, after <a href="https://newsroom.fb.com/news/2017/10/update-on-our-advertising-transparency-and-authenticity-efforts/">they’ve promised to be more transparent about all of this</a>. Also, the sneaky nature of the API deprecation, which isn’t unusual for Facebook reveals their true motivation. The deprecation is only published in AdWeek, and clearly is something other outlets are either unaware of, or unwilling to talk about due to retribution by Facebook, which might limit your exposure on the network. Facebook has many news outlets by the balls when it comes to platform exposure these days, potentially limiting who will be critical of the platform.

<p>The Facebook Audience Insights API represents the conundrum of APIs for me. If APIs don’t exist we can’t see into the algorithms that are increasingly governing our lives. If they do exist then people with ill intentions get access to them, and can use them for shady things like we’ve been seeing as part of the election. The answer? They should exist, but then provide access by auditors, regulators, researchers, and journalists to see what is possible via platforms. Then, EVERYONE who has access to the tools should be observable and accountable. Not just the APIs, but also the web interface. If you are developing models that target a demographic, that demographic should know about it, and auditors, researchers, and journalists should have API access to all of this, so that they can assess and report on what is going on. The watchers should also be accountable. This is why I do APIs, not because I believe they are always good, but because they provide us with secure, managed, accountable observability into how platforms and algorithms work (or don’t).

<p>Ideally, tools like this do not exist in the first place. My feeling is that we burn it down. However, I know this isn’t a reality. My next recommendation is that ALL advertising platforms possess APIs for ALL aspects of operations, with access tiers for auditors, regulators, researchers, and journalists. Observability into how these platforms are operating is the only way we can move this conversation forward in a way that protects the end-users of platforms from harm. It is clear that Facebook is not interested in true observability, and are playing the usual transparency games by acting like they are self-regulating, but then just pulling the curtains on what they are up to. In coming years, we’ll see more APIs be deprecated because of this, as the platforms realizing what is possible, and just commence more secretive about what they do. The cat is out of the bag. The technology exists to give us visibility into what is going on, the trick is going to be all about keeping the APIs that exist operational, and delivering 100% coverage of platform operations, and regulating that APIs be introduced where they do not exist already. Sorry platforms, you had plenty of time to be straight up about this stuff, and you chose not to.


