---
published: true
layout: post
title: 'The Importance Of Postman API Environment Files'
image: https://s3.amazonaws.com/kinlane-productions2/postman/postman-environments.png
---

<p><img src="https://s3.amazonaws.com/kinlane-productions2/postman/postman-environments.png" width="45%" align="right" style="padding: 15px;" />
<p>I’m a big fan of <a href="https://www.postman.com/">Postman</a>, and the power of their development environment, as well as their Postman Collection format. I think their approach to not just integrating with APIs, but also enabling the development and delivery of APIs has shifted the conversation around APIs in the last couple of years–not too many API service providers accomplish this in my experience. There are several dimensions to what Postman does that I think are pushing the API conversation forward, but one that has been capturing my attention lately <a href="https://www.postman.com/docs/v6/postman/environments_and_globals/manage_environments">are Postman Environment Files</a>.

<p>Using Postman, you can manage many different environments used for working with APIs, and if you are a pro or enterprise customer, you can export a file that represents an environment, making each of these API definitions more portable and collaborative. Managing the variety of environments for the hundreds of APIs I use is one of the biggest pain points I have. Postman has significantly helped me get a handle on the tokens and keys I use across the internal, as well as partner and public APIs that I depend on each day to operate API Evangelist.

<p>Postman environments allows me to define environments within the Postman application, and then share them as part of the pro / enterprise team experience. <a href="https://docs.api.postman.com/#a237ffbe-0444-b394-a2c4-b99f691931cf">You can also manage your environments through the Postman API</a>, if you need to more deeply integrate with your operations. The Postman Environment File makes all of this portable, sharable, and used across environments. It is one of the reasons that makes Postman Collections more valuable to some users, in specific contexts, because it has that run time aspect to what it does. Postman let’s you communicate effectively around the APIs you are deploying and integrating with, and solves relevant pain points like API environment management, that can stand in the way of integration.

<p>There aren’t many features of API service providers I get very excited about, but the potential of Postman as an environment management solution is significant. If Postman is able to establish itself as the broker of credentials at the API environment level, it will give them a significant advantage of other service providers. With the size of their developer base, having visibility at the environment level puts their finger on the pulse of what is going on in the API economy, from both an API provider and consumer perspective. With Postman Environment Files acting as a sort of key, or currency, that has to exist before any API transaction can be executed. And, as the number of APIs we depend on increases, the importance of having a strategy (and solution) for managing our environment will grow exponentially–putting Postman in a pretty sweet position.

