---
published: true
layout: post
title: 'Join Me For A Fireside Chat At The Paris API Meetup This Wednesday'
image: https://s3.amazonaws.com/kinlane-productions2/events/paris-api-meetup/DqJd3bkJ.jpeg
---

<p><a href="https://www.meetup.com/ParisAPI/events/255614957/"><img src="https://s3.amazonaws.com/kinlane-productions2/events/paris-api-meetup/DqJd3bkJ.jpeg" width="45%" align="right" style="padding: 15px;" /></a>
<p>I am in Europe for most of October, and while I am in Paris we thought it would be a good idea to pull together a last minute API Meetup. Romain Simiand (<a href="https://twitter.com/RomainSimiand">@RomainSimiand</a>), the API Evangelist at <a href="https://www.people-doc.com/">PeopleDoc</a> was gracious enough to help pull things together, and the <a href="http://streamdata.io">Streamdata.io</a> team is stepping up to help with food and drink. Pulling together a last minute gathering at PeopleDoc in Paris, and bringing me on stage to talk about the technology, business, and politics of APIs, well as about some of my recent work on API discovery, and event-driven architecture.

<p><a href="https://www.meetup.com/ParisAPI/events/255614957/">You can find more details on the Paris API Meetup site</a>, with directions on how to find PeopleDoc. Make sure you RSVP so that we know you are coming, and of course, please help spread the word. We are over 30 people attending so far, but I think we can do better. I’m happy to get on stage and help drive the API discussion, but I’d prefer to have a healthy representation of the Paris API community asking questions, helping me understand what is happening across the area when it comes to APIs. I always have plenty of knowledge to share, but it becomes exponentially more valuable when people on the ground within communities are asking questions, and making it relevant to what is happening within the day to day operations of companies in the local area.

<p>While I enjoy doing conference keynotes and panels, my favorite format of event is the Meetup. Bringing together less than 100 people have a discussion about APIs. I always find that I learn the most in this environment, and able to actually engage with developers and business folks about what really matters when it comes to APIs. The larger the audience the more it is just about me broadcasting my message, and when it is a smaller and more intimate venue, I feel like I can better connect with people. In my opinion, this is how all API events should be–small, intimate, and a real world conversation about APIs. Not just an API pundit pushing their thoughts out, ensuring that all participants feel like they are actually part of the conversation.

<p>If you are in the Paris region, or can make the time to hope on a plane or train and make it to Paris this Wednesday, I love to hang out. If you can’t make it, I’ll be back for API Days Paris in December, but it will be a bigger event, and it might be more difficult to carve out the time to hang. So, bring your API questions, and come over to the PeopleDoc office this Wednesday, and we’ll have a proper discussion about the technology, business, or politics of APIs. Helping drive the API discussion going on in France, continuing to push it forward. Making France a leader when it comes to doing business in the growing API economy. I look forward to seeing you all in Paris this week!

