---
published: true
layout: post
title: 'API Copyright: Directories'
image: https://s3.amazonaws.com/kinlane-productions2/algorotoscope-master/aws-s3-stories-containership-dali-three.jpg
---
<p><img style="padding: 15px;" src="https://s3.amazonaws.com/kinlane-productions2/algorotoscope-master/aws-s3-stories-containership-dali-three.jpg" alt="" width="40%" align="right" /></p>
<p class="p1"><span class="s1"><a href="http://apievangelist.com/2019/11/17/api-copyright-heading-to-the-supreme-court/">I am gearing up for API copyright heading to the Supreme Court</a></span>, having another look at whether or not the naming and ordering of your API interface is copyrightable, as well as whether or not reimplementation of it can be considered fair use. To help strengthen my arguments that API should not be copyrightable I wanted to work through my thoughts about how APIs are similar to other existing concepts that are not copyrightable. One of the newer concepts I&rdquo;m working with to help strengthen my argument that copyright does not apply to APIs involves the directory, and shining a light on the fact that APIs are just a directory of our digital resources.</p>
<p class="p1">As with all of my API storytelling, I am focused exclusively on web API. Occasionally you&rsquo;l hear me talking about language and platform SDK APIs, browser APIs, and other variations, but the majority of what I mean when I say API is done via public DNS over HTTP, HTTP/2, and sometimes TCP. All of these APIs are just a directory of <a href="https://en.wikipedia.org/wiki/Uniform_Resource_Identifier">Uniform Resource Identifiers (URIs)</a>&nbsp;of corporate and institutional digital assets. Modern APIs most often leverage DNS, providing a machine readable listing of resources that are available within a specific domain. The domain and the resulting API directory are not creative expressions, they are an address that points to a directory of digital assets, allowing them to be found by developers for use in other applications and systems. APIs are not a form of creative expression, they are just helping companies, organizations, institutions, and government agencies make their digital resources and capabilities discoverable.</p>
<p class="p1">I can easily make the argument that APIs are simply a directory or menu of organizational resources and capabilities. Due to the diverse nature of what an API can be, I can also easily apply the analogy that APIs are also recipes. All the above is true. As with my restaurant menu and recipe stories, people have trouble believing that APIs are copyrightable because they struggle with separating the API from the data, content, media, algorithms, and processes being delivered using APIs. It is unlikely that your data is copyrightable, but the content and media might be. Your algorithms and processes behind the APIs might also be protected using patents. However, your directory for finding this intellectual property is not something that falls under copyright. Your API is just how you and your partners will discover, access, and put the valuable intellectual property for your organization to work wherever it is needed online.</p>
<p class="p1">APIs will continue to play an important role in defining copyrighted and patented intellectual property, but they should not be considered part of the portfolio. They simply are about access to the business IP portfolio, providing an authenticated, rate limited, logged, audible, and monetizable directory that governs how digital assets are used across desktop, web, mobile, device, and network applications. If the Supreme Court properly scrutinizes the layers of modern API infrastructure that is behind almost all applications in use online today, they will understand the nuances of how APIs do what they do, and begin to see how it important it is to keep this directory layer of the online economy well greased and open for business. If we allow an IP thicket to emerge at the integration layer of the web it will only work in favor of large tech companies, and lock out the smaller startups who are responsible for much of the innovation we have seen over the last twenty years.</p>
